### ISSUE TITLE
jersey-container-servlet-core 2.25.1 is used over jersey-container-servlet 2.27 in KumuluzEE 3.0.0

### ISSUE THREAD

**Issue by Mulgish** [kumuluz/kumuluzee-swagger#6]
If kumuluzee 3.0.0 is used with kumuluzee-swagger 1.2.0 or below, a wrong dependency is used by server which causes exceptions on startup.
Current workaround is to exclude jersey-container-servlet-core 2.25.1 from kumuluzee-swagger.

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.kumuluz.ee</groupId>
                <artifactId>kumuluzee-bom</artifactId>
                <version>3.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.kumuluz.ee</groupId>
            <artifactId>kumuluzee-microProfile-1.2</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kumuluz.ee.swagger</groupId>
            <artifactId>kumuluzee-swagger</artifactId>
            
            
                
                    
                    
                
            
            <version>1.2.0</version>
        </dependency>

2018-11-13 09:19:41.045 WARNING -- org.eclipse.jetty.webapp.WebAppContext -- Failed startup of context o.e.j.w.WebAppContext@5d10455d{/,file:///C:/lgim/code/order-raising-service/target/classes/webapp/,UNAVAILABLE}
java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Predicate
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:670)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:427)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:374)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:848)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.kumuluz.ee.jetty.JettyServletServer.startServer(JettyServletServer.java:81)
	at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:368)
	at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:73)
	at com.kumuluz.ee.EeApplication.main(EeApplication.java:85)
Caused by: java.lang.ClassNotFoundException: jersey.repackaged.com.google.common.base.Predicate
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more

If guava dependency is added manually, hk2 dependency errors can be observed later on.

**Comment by zvonegit** [comment]
Hi there,

I was not able to reproduce your issue however, I did make some changes an provided a new version of extension where jersey-container-servlet-core from kumuluzee framework is forced. 

Can you test with pre-release [v1.2.1](https://github.com/kumuluz/kumuluzee-swagger/releases/tag/v1.2.1).

**Comment by Mulgish** [comment]
Hi Zvone,

I can confirm that the issue is gone in version 1.2.1.

**Comment by Mulgish** [comment]
When 1.2.1 is going to be released?

**Comment by zvonegit** [comment]
v1.2.1 is now a final release.
